### ISSUE TITLE
`BSD-3` license not recognized

### ISSUE THREAD

**Issue by perazz** [fortran-lang/registry#30]
Low priority issue. 

I'm playing with the `fpm publish` command a bit and I've found that [fitpack](https://github.com/perazz/fitpack) cannot be uploaded: 

```
federico@Federicos-MBP fitpack % fpmx publish --token=XXXXXX
 Uploading package ...
{"code":400,"message":"Invalid license identifier"}
```

The license in fpm.toml is `BSD-3`. Any hints @arteevraina @henilp105 ?

**Comment by minhqdao** [comment]
The license has to be specified in the [SPDX format](https://spdx.org/licenses/BSD-3-Clause.html). Try `BSD-3-Clause`. That should work.

**Comment by perazz** [comment]
I think `fpm` should definitely prompt it to the user, I believe that was part of the package validation effort, what is its status?

**Comment by henilp105** [comment]
Thanks @perazz @minhqdao , I have patched this here: https://github.com/henilp105/registry/commit/3e998c214d8c9333eb4f28b5023eacb34265f9b55 , this will notify the user for the spdx license requirement.

**Comment by arteevraina** [comment]
> I see. I think `fpm` should definitely prompt it to the user then, I believe that was part of the package validation effort, what is its status?

I think the fact that `registry` is allowing to upload packages with only [`spdx-license`](https://spdx.org/licenses/) identifiers is itself one of steps of package validation. 

Regarding this requirement it has been quickly solved by @henilp105. Should be there in subsequent backend releases.
https://github.com/fortran-lang/registry/pull/28/commits/3e998c214d8c9333eb4f28b5023eacb34265f9b5#diff-057993efe883364e92663f0d8fa5d1bcfcaee943d6dce70eb2b64ef1ecb5a2e6R152

**Comment by perazz** [comment]
Fantastic @henilp105, thank you! Looks good to me.
