### ISSUE TITLE
Support `zip`

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/registry#40]
It would be great to support both `tar` and `zip` formats and it should be easy to add that on the backend, too. Just allow the user to upload and download a `zipball` equivalent to a `tarball`.

**Comment by henilp105** [comment]
Hi @minhqdao , I have added support for both zipballs and tarballs , the backend will automatically detect the zipball or the tarball and set the file MIME type and upload settings.

**Comment by minhqdao** [comment]
Great, if you add validation of the packages on the backend, you could unpack both zip- and tarball and make sure that both are identical.

**Comment by henilp105** [comment]
@minhqdao I think that we should only allow to upload anyone of them , uploading both would lead to security issues as we have to verify both of them to be exactly same for each element in that tarball/zipball and also lead to redundancy in database and most of the devices have the ability to handle atleast one of them.

**Comment by minhqdao** [comment]
Well, the idea was to offer more downloadable format options. Therefore redundancy in the database is intended. If we currently don't have verification on the backend, then it's probably better to just stick with tarballs.

**Comment by henilp105** [comment]
@minhqdao yes , I think we should give more downloadable options I would suggest that we let the user upload anyone of the zip/tarball then we during the upload directly unzip/untar it to convert into another format and save it in the db the on the download side we could directly give the option for both. (alteast this would help reduce the verification to only 1 tar/zipball and also remove the need for the zip/tarball comparision) .

**Comment by minhqdao** [comment]
> @minhqdao yes , I think we should give more downloadable options I would suggest that we let the user upload anyone of the zip/tarball then we during the upload directly unzip/untar it to convert into another format and save it in the db the on the download side we could directly give the option for both. (alteast this would help reduce the verification to only 1 tar/zipball and also remove the need for the zip/tarball comparision) .

I was also thinking about that. We should it that way.
