### ISSUE TITLE
Reset Password Link.

### ISSUE THREAD

**Issue by arteevraina** [fortran-lang/registry#43]
The reset password link that I receive and when I make a GET request to this url. I get a Not Found error.

For example : 

```
    Dear arteevraina,

    We received a request to reset your password. To reset your password, please copy paste the link below in a new browser window:

    localhost/account/reset-password/7bbb451c7b514c59a8ce00fb5fa586e8

    Thank you,
    The Fortran-lang Team
```

**Comment by arteevraina** [comment]
cc: @henilp105

**Comment by henilp105** [comment]
This error is due to the local host `port` not found , to configure for the local host you would have to enter the port of the frontend for the email reset password functionality. ( this is automatically handled for the hosting like vercel and AWS ) .

**Comment by henilp105** [comment]
@arteevraina you would have to set the env var `host` to the frontend base url ( for vercel) and set it to the localhost frontend url ( for local host).

**Comment by arteevraina** [comment]
Thanks @henilp105 . Works for me.

**Comment by minhqdao** [comment]
Works now, therefore closed this.
