### ISSUE TITLE
Cannot Search fpm package

### ISSUE THREAD

**Issue by rajkumardongre** [fortran-lang/registry#49]
Hi, I am trying to search the fpm package form [home page](https://registry-frontend.vercel.app/), but the page is just keep loading.

here is the image after inspect:
![image](https://github.com/fortran-lang/registry/assets/77038993/2aa12af2-663a-434e-913b-f11471165e5a)

**Comment by gnikit** [comment]
The registry is offline, after the public-beta was concluded this summer. We will be bringing bring it online once we complete some internal organisational tasks.

**Comment by henilp105** [comment]
We will be soon bringing a dev version of the registry for another round of testing and preview. 

Thanks and Regards,
Henil Panchal

**Comment by rajkumardongre** [comment]
Cool
